### ISSUE TITLE
License violation in copyright statement changes

### ISSUE THREAD

**Issue by jagerman** [Vaizon-Project/vaizon#3]
Hi,

While Loki is a permissively licensed open source that you are free to fork, rename, and modify however you like, one of the very few requirements of the license is:

> 1. Redistributions of source code **must retain the above copyright notice,** this list of conditions and the following disclaimer.

By replacing "The Loki Project" copyright notices in various files in the source code such as these:

https://github.com/Vaizon-Project/vaizon/blob/dbd0447a6e35cf5a53b747137114873ac7eff89e/LICENSE#L2
https://github.com/Vaizon-Project/vaizon/blob/dbd0447a6e35cf5a53b747137114873ac7eff89e/src/cryptonote_core/service_node_list.h#L1
https://github.com/Vaizon-Project/vaizon/blob/dbd0447a6e35cf5a53b747137114873ac7eff89e/src/cryptonote_protocol/quorumnet.h#L1

and many others throughout the repository, you are in violation of Loki's free software license and are thus committing copyright infringement by redistributing the Loki source code without license.  Please rectify this immediately by restoring all of the Loki Project's copyright statements in the above file and all others where it was changed to be in compliance with the free software license.  You may, of course, add your own copyright statements to the various files, but under the terms of the license may not remove ours (or Monero's) from the license file or the code.

Thank you,
Jason Rhinelander
Loki developer & Loki Foundation director

**Comment by Edward-pops** [comment]
We have update the copyright.
